vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set autoread")
vim.cmd("nnoremap ß $")
vim.cmd("vnoremap ß $")
vim.cmd("vnoremap > >gv")
vim.cmd("vnoremap < <gv")
vim.cmd("vnoremap <Tab> >gv")
vim.cmd("vnoremap <S-Tab> <gv")
vim.cmd("tnoremap <Esc> <C-\\><C-n>")
vim.g.mapleader = " "
