[font]
size = 11.0

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 1
padding = {x=8, y=8}

# Colors (Gruvbox Material Dark Medium)
[colors.primary]
foreground = '#d4be98'
background = '#282828'

[colors.normal]
black ='#665c54'
red = '#ea6962'
green = '#a9b665'
yellow = '#e78a4e'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

[colors.bright]
black = '#928374'
red = '#ea6962'
green = '#a9b665'
yellow = '#e3a84e'
blue =  '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'


# Colors (Gruvbox)
# [colors.primary]
# foreground = '#ebdbb2'
# background = '#282828'

# [colors.normal]
# black = '#282828'
# red = '#cc241d'
# green = '#98971a'
# yellow = '#d79921'
# blue = '#458588'
# magenta = '#b16286'
# cyan = '#689d6a'
# white = '#a89984'

# [colors.bright]
# black = '#928374'
# red = '#fb4934'
# green = '#b8bb26'
# yellow = '#fabd2f'
# blue = '#83a598'
# magenta = '#d3869b'
# cyan = '#8ec07c'
# white ='#ebdbb2'


# color experiments:)

#[colors.bright]
#black = "#545454"
#blue = "#94bff3"
#cyan = "#93e0e3"
#green = "#8ae234"
#magenta = "#b294bb"
#red = "#fc5454"
#white = "#ffffff"
#yellow = "#fce94f"

#black = "#133912"
#blue = "#72924A"
#cyan = "#809F52"
#green = "#87A757"
#magenta = "#785B85"
#red = "#9766A7"
#white = "#B471C9"
#yellow = "#d9b2e4"

#[colors.normal]
#black = "#3f3f3f"
#blue = "#94bff3"
#cyan = "#06989a"
#green = "#4e9a06"
#magenta = "#85678f"
#red = "#cc0000"
#white = "#dcdccc"
#yellow = "#c4a000"

#black = "#977c9f"
#blue = "#72924A"
#cyan = "#809F52"
#green = "#87A757"
#magenta = "#785B85"
#red = "#9766A7"
#white = "#B471C9"
#yellow = "#d9b2e4"

#[colors.primary]
#background = "#222222"
#foreground = "#F9F9F9"

#background = "#133912"
#foreground = "#87a757"

#background = "#133912"
#foreground = "#d9b2e4"
