server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[dmenu]
line_length = 100
menu_length = 0
menu_prompt = "Remove from Clipboard History:"
extra_arguments = ["-i"]

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
